name = "TGGeometry"
uuid = "d7e755d2-3c95-4bcf-9b3c-79ab1a78647b"
authors = ["Anshul Singhvi <anshulsinghvi@gmail.com> and contributors"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
GeoInterface = "cf35fbd7-0cd7-5166-be24-54bfbe79505f"
tg_jll = "d3b19594-2c4a-559a-8374-9f5b4f4149ad"

[compat]
CEnum = "0.5"
GeoInterface = "1.4"
tg_jll = "0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
